import { ArrowLeft, CalendarDays, Check, CircleAlert, Droplets, Leaf, Printer, Sprout, TrendingUp } from 'lucide-react';
import { useGetAdvisory, getGetAdvisoryQueryKey } from '@workspace/api-client-react';
import { useLocation, useParams } from 'wouter';
import { AgroShell, DataPill, ErrorState, LoadingBlocks } from '@/components/agro-shell';
import { Button } from '@/components/ui/button';

const req = (userId: string | null) => ({ headers: { 'x-user-id': userId ?? '' } });

export default function AdvisoryDetail({ userId }: { userId: string | null }) {
  const params = useParams<{ id: string }>();
  const [, setLocation] = useLocation();
  const id = params.id ?? '';
  const query = useGetAdvisory(id, { query: { enabled: !!id && !!userId, queryKey: getGetAdvisoryQueryKey(id) }, request: req(userId) });
  const advisory = query.data;
  return <AgroShell userId={userId}><div className="print-report page-enter mx-auto max-w-[1120px] px-5 py-9 sm:px-8 lg:px-10 lg:py-12">
    <div className="no-print mb-8 flex items-center justify-between"><button onClick={() => setLocation('/dashboard')} className="inline-flex items-center gap-2 text-xs font-bold text-muted-foreground hover:text-foreground" data-testid="button-back-dashboard"><ArrowLeft className="size-3.5" /> Back to overview</button><Button variant="outline" size="sm" onClick={() => window.print()} className="gap-2" data-testid="button-print-advisory"><Printer className="size-3.5" /> Print report</Button></div>
    {query.isLoading ? <LoadingBlocks count={5} /> : query.isError || !advisory ? <ErrorState message="This advisory is not available." /> : <><header className="border-b border-border pb-8"><div className="flex flex-wrap items-center gap-2"><DataPill tone="blue">{advisory.targetSeason} season</DataPill><DataPill tone="gold">{advisory.budgetLevel} budget</DataPill><span className="ml-1 text-xs text-muted-foreground">Field note / {advisory.id.slice(0, 8)}</span></div><h1 className="display-serif mt-5 max-w-4xl text-5xl leading-[.92] tracking-[-.045em] sm:text-7xl" data-testid="text-advisory-title">A plan for<br /><em className="text-primary">{advisory.farmName}</em></h1><div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><ArrowLeft className="size-3 rotate-180" /> {advisory.region}</span><span className="flex items-center gap-1.5"><CalendarDays className="size-3.5" /> Prepared {formatDate(advisory.createdAt)}</span></div></header>
      <section className="grid gap-7 py-9 lg:grid-cols-[1.15fr_.85fr]"><div><p className="mono-label text-[hsl(var(--chart-3))]">The question you brought</p><blockquote className="display-serif mt-3 max-w-2xl text-3xl leading-tight text-foreground">“{advisory.specificConcerns || 'What should this field grow next?'}”</blockquote></div><div className="rounded-2xl bg-primary p-5 text-primary-foreground"><p className="mono-label text-primary-foreground/55">Reading guide</p><p className="mt-3 text-sm leading-6 text-primary-foreground/80">Start with the crop fit, then use the preparation and management steps as your working sequence.</p></div></section>
      <section className="border-t border-border pt-9"><SectionHeading icon={Sprout} eyebrow="01 / crop fit" title="Recommended crops" /><div className="mt-5 grid gap-4">{advisory.report.recommendedCrops.map((crop, index) => <div key={crop.cropName} className="grid gap-5 rounded-2xl border border-border bg-card p-5 paper-shadow sm:grid-cols-[70px_1fr_170px] sm:items-center sm:p-6" data-testid={`card-recommendation-${index}`}><div className="flex size-[62px] flex-col items-center justify-center rounded-2xl bg-secondary"><span className="font-mono text-2xl font-bold text-primary">{crop.suitabilityScore}</span><span className="text-[9px] font-bold uppercase text-muted-foreground">fit</span></div><div><h3 className="text-lg font-bold">{crop.cropName}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{crop.reasoning}</p><div className="mt-3 h-1.5 max-w-[330px] overflow-hidden rounded-full bg-secondary"><div className={`h-full rounded-full ${index === 0 ? 'bg-primary' : 'bg-[hsl(var(--chart-3))]'}`} style={{ width: `${crop.suitabilityScore}%` }} /></div></div><div className="grid grid-cols-2 gap-3 border-t border-border pt-4 sm:block sm:border-l sm:border-t-0 sm:pl-5 sm:pt-0"><div><p className="mono-label text-muted-foreground">Yield / acre</p><p className="mt-1 text-sm font-bold">{crop.expectedYieldPerAcre}</p></div><div className="mt-3"><p className="mono-label text-muted-foreground">Est. ROI</p><p className="mt-1 flex items-center gap-1 text-sm font-bold text-[hsl(var(--chart-3))]"><TrendingUp className="size-3.5" /> +{crop.estimatedRoiPercentage}%</p></div></div></div>)}</div></section>
      <section className="grid gap-8 border-t border-border py-10 lg:grid-cols-2"><div><SectionHeading icon={Leaf} eyebrow="02 / prepare" title="Soil preparation" /><div className="mt-5 space-y-3">{advisory.report.soilPreparationSteps.map((step, index) => <div key={step} className="flex gap-3 rounded-xl bg-secondary/60 p-4" data-testid={`text-soil-step-${index}`}><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-primary text-[11px] font-bold text-primary-foreground">{index + 1}</span><p className="text-sm leading-6">{step}</p></div>)}</div></div><div><SectionHeading icon={Droplets} eyebrow="03 / water" title="Irrigation schedule" /><div className="mt-5 rounded-2xl border border-[hsl(var(--chart-3)/.28)] bg-[hsl(var(--chart-3)/.07)] p-5"><p className="text-sm leading-7" data-testid="text-irrigation-schedule">{advisory.report.irrigationSchedule}</p></div></div></section>
      <section className="border-t border-border py-10"><SectionHeading icon={CircleAlert} eyebrow="04 / protect" title="Pest & disease management" /><div className="mt-5 grid gap-4 md:grid-cols-2">{advisory.report.pestDiseaseManagement.map((threat, index) => <div className="rounded-2xl border border-border bg-card p-5" key={threat.threatName} data-testid={`card-threat-${index}`}><h3 className="font-bold">{threat.threatName}</h3><div className="mt-4 space-y-3 text-sm leading-6"><p><span className="font-bold text-primary">Prevention:</span> {threat.preventionStrategy}</p><p><span className="font-bold text-[hsl(var(--chart-3))]">Treatment:</span> {threat.treatment}</p></div></div>)}</div></section>
      <section className="border-t border-border pb-6 pt-10"><SectionHeading icon={Check} eyebrow="05 / keep the soil" title="Sustainability notes" /><div className="mt-5 grid gap-3 sm:grid-cols-2">{advisory.report.sustainabilityTips.map((tip, index) => <div className="flex gap-3 rounded-xl border border-border bg-card p-4" key={tip} data-testid={`text-sustainability-tip-${index}`}><Check className="mt-0.5 size-4 shrink-0 text-[hsl(var(--chart-3))]" /><p className="text-sm leading-6">{tip}</p></div>)}</div></section>
      <footer className="border-t border-border pt-6 text-xs text-muted-foreground"><span className="font-bold text-foreground">AgroBrain</span> · A field note prepared from your farm profile and stated priorities.</footer>
    </>}
  </div></AgroShell>;
}

function SectionHeading({ icon: Icon, eyebrow, title }: { icon: typeof Sprout; eyebrow: string; title: string }) { return <div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-secondary text-primary"><Icon className="size-[17px]" /></span><div><p className="mono-label text-[hsl(var(--chart-3))]">{eyebrow}</p><h2 className="display-serif mt-0.5 text-3xl tracking-[-.03em]">{title}</h2></div></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat('en', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(value)); }