import { Link } from 'wouter';
import { ArrowUpRight, ChevronRight, Droplets, MapPin, Plus, Sprout, Wheat } from 'lucide-react';
import { useGetDashboardSummary, useListAdvisories, useListFarms, getGetDashboardSummaryQueryKey, getListAdvisoriesQueryKey, getListFarmsQueryKey } from '@workspace/api-client-react';
import { AgroShell, DataPill, EmptyState, ErrorState, GoLink, LoadingBlocks, PageHeader } from '@/components/agro-shell';

type Props = { userId: string | null };
const req = (userId: string | null) => ({ headers: { 'x-user-id': userId ?? '' } });

export default function Dashboard({ userId }: Props) {
  const summaryQuery = useGetDashboardSummary({ query: { enabled: !!userId, queryKey: getGetDashboardSummaryQueryKey() }, request: req(userId) });
  const farmsQuery = useListFarms({ query: { enabled: !!userId, queryKey: getListFarmsQueryKey() }, request: req(userId) });
  const advisoriesQuery = useListAdvisories({ query: { enabled: !!userId, queryKey: getListAdvisoriesQueryKey() }, request: req(userId) });
  const summary = summaryQuery.data;
  const farms = summary?.farms ?? farmsQuery.data ?? [];
  const advisories = advisoriesQuery.data ?? [];
  const loading = summaryQuery.isLoading || farmsQuery.isLoading || advisoriesQuery.isLoading;
  return <AgroShell userId={userId}><div className="page-enter mx-auto max-w-[1440px] px-5 py-9 sm:px-8 lg:px-10 lg:py-12">
    <PageHeader eyebrow="Field overview" title="Good morning, farmer." description="Your farms and recent thinking, in one place." action={<Link href="/advisory/generate" className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground shadow-sm transition-transform hover:-translate-y-0.5" data-testid="link-create-advisory"><Plus className="size-4" /> Generate advisory</Link>} />
    {loading ? <LoadingBlocks count={4} /> : summaryQuery.isError ? <ErrorState /> : <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Metric label="Farm profiles" value={summary?.farmCount ?? farms.length} note="in your workspace" icon={MapPin} tone="olive" />
      <Metric label="Advisories made" value={summary?.advisoryCount ?? advisories.length} note="field notes to date" icon={Wheat} tone="gold" />
      <Metric label="Average suitability" value={`${Math.round(summary?.averageSuitability ?? 0)}`} suffix="/100" note="across recommendations" icon={Sprout} tone="blue" />
      <div className="rounded-2xl bg-primary p-5 text-primary-foreground shadow-lg shadow-primary/10"><p className="mono-label text-primary-foreground/55">Next useful step</p><p className="mt-3 text-sm font-semibold leading-6">Add a farm profile or generate a seasonal plan.</p><Link href={farms.length ? '/advisory/generate' : '/farms/new'} className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-accent" data-testid="link-next-step">Continue <ArrowUpRight className="size-3.5" /></Link></div>
    </section>
    <section className="mt-10 grid gap-8 xl:grid-cols-[1.25fr_.75fr]">
      <div><div className="mb-4 flex items-end justify-between"><div><p className="mono-label text-[hsl(var(--chart-3))]">Your ground</p><h2 className="display-serif mt-1 text-3xl tracking-[-.03em]">Farm profiles</h2></div><Link href="/farms/new" className="text-xs font-bold text-primary hover:underline" data-testid="link-add-farm"><Plus className="mr-1 inline size-3.5" /> Add farm</Link></div>
        {farms.length ? <div className="grid gap-3 sm:grid-cols-2">{farms.map((farm, index) => <Link href={`/advisory/generate?farm=${farm.id}`} key={farm.id} className={`group relative overflow-hidden rounded-2xl border border-border bg-card p-5 paper-shadow transition-all hover:-translate-y-1 hover:border-primary/40 ${index === 0 ? 'sm:col-span-2 sm:p-6' : ''}`} data-testid={`card-farm-${farm.id}`}><div className="absolute right-0 top-0 h-full w-1/3 bg-gradient-to-l from-[hsl(var(--accent)/.12)] to-transparent opacity-70" /><div className="relative flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className={`font-bold ${index === 0 ? 'text-lg' : ''}`}>{farm.name}</h3><DataPill tone="olive">{farm.soilType}</DataPill></div><p className="mt-2 flex items-center gap-1.5 text-sm text-muted-foreground"><MapPin className="size-3.5" />{farm.region} <span className="text-border">·</span> {farm.areaAcres} acres</p></div><span className="flex size-8 items-center justify-center rounded-full bg-secondary text-primary transition-transform group-hover:translate-x-1"><ChevronRight className="size-4" /></span></div><div className="relative mt-6 flex flex-wrap gap-x-6 gap-y-2 border-t border-border/70 pt-4 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Droplets className="size-3.5 text-[hsl(var(--chart-3))]" /> {farm.irrigationMethod}</span><span>Climate: {farm.climateZone}</span><span>Previous: {farm.historicCrop}</span></div></Link>)}</div> : <EmptyState title="Start with the ground beneath you." description="Add your first farm profile so recommendations can account for the details that make your field different." action={<Link href="/farms/new" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground" data-testid="link-empty-add-farm"><Plus className="size-4" /> Add a farm</Link>} />}
      </div>
      <div><div className="mb-4 flex items-end justify-between"><div><p className="mono-label text-[hsl(var(--chart-3))]">Recent thinking</p><h2 className="display-serif mt-1 text-3xl tracking-[-.03em]">Advisories</h2></div>{advisories.length > 0 && <span className="text-xs text-muted-foreground">{advisories.length} total</span>}</div>
        {advisories.length ? <div className="divide-y divide-border overflow-hidden rounded-2xl border border-border bg-card">{advisories.slice(0, 5).map(item => <Link href={`/advisory/${item.id}`} key={item.id} className="group block p-4 transition-colors hover:bg-secondary/50" data-testid={`row-advisory-${item.id}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">{item.farmName}</p><p className="mt-1 text-xs text-muted-foreground">{item.targetSeason} season <span className="mx-1">·</span> {item.budgetLevel} budget</p></div><span className="font-mono text-lg font-bold text-primary">{item.topScore}<span className="text-[10px] text-muted-foreground">/100</span></span></div><div className="mt-4 flex items-center justify-between text-xs"><span className="flex items-center gap-1.5 font-semibold text-[hsl(var(--chart-3))]"><Sprout className="size-3.5" /> {item.topCrop}</span><span className="text-muted-foreground">{formatDate(item.createdAt)}</span></div></Link>)}</div> : <EmptyState title="No field notes yet." description="Generate an advisory to turn one of your farm profiles into a seasonal plan." action={farms.length ? <Link href="/advisory/generate" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground" data-testid="link-empty-advisory">Make an advisory <ArrowUpRight className="size-4" /></Link> : undefined} />}
      </div>
    </section>
    {summary?.latestAdvisory && <section className="mt-8 flex flex-col justify-between gap-5 rounded-2xl border border-[hsl(var(--chart-3)/.28)] bg-[hsl(var(--chart-3)/.07)] p-5 sm:flex-row sm:items-center sm:p-6"><div><p className="mono-label text-[hsl(var(--chart-3))]">Last recommendation</p><p className="mt-2 font-semibold">{summary.latestAdvisory.topCrop} is the strongest fit for {summary.latestAdvisory.farmName}.</p></div><GoLink href={`/advisory/${summary.latestAdvisory.id}`}>Read the full advisory</GoLink></section>}
    </>}
  </div></AgroShell>;
}

function Metric({ label, value, suffix, note, icon: Icon, tone }: { label: string; value: number | string; suffix?: string; note: string; icon: typeof MapPin; tone: 'olive' | 'gold' | 'blue' }) {
  const iconStyle = { olive: 'bg-primary/10 text-primary', gold: 'bg-accent/25 text-[hsl(var(--accent-foreground))]', blue: 'bg-[hsl(var(--chart-3)/.14)] text-[hsl(var(--chart-3))]' };
  return <div className="rounded-2xl border border-border bg-card p-5 paper-shadow"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-extrabold tracking-[-.06em]">{value}{suffix && <span className="ml-1 text-base font-semibold text-muted-foreground">{suffix}</span>}</p></div><span className={`flex size-9 items-center justify-center rounded-xl ${iconStyle[tone]}`}><Icon className="size-[17px]" /></span></div><p className="mt-3 text-[11px] text-muted-foreground">{note}</p></div>;
}

function formatDate(value: string) { return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric' }).format(new Date(value)); }