import { Link } from 'wouter';
import { ArrowRight, Check, Droplets, LineChart, ShieldCheck, Sprout, SunMedium } from 'lucide-react';
import { Mark } from '@/components/agro-shell';

export default function Landing() {
  return <div className="app-grain min-h-[100dvh] overflow-hidden bg-background text-foreground">
    <header className="relative z-10 flex items-center justify-between px-6 py-6 sm:px-10 lg:px-16"><Mark /><div className="flex items-center gap-5"><span className="hidden text-sm text-muted-foreground sm:block">A practical second opinion for the field</span><Link href="/dashboard" className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-4 py-2 text-sm font-bold shadow-sm hover:bg-secondary" data-testid="link-enter-workspace">Enter workspace <ArrowRight className="size-4" /></Link></div></header>
    <main>
      <section className="relative px-6 pb-20 pt-16 sm:px-10 sm:pt-24 lg:px-16 lg:pb-28">
        <div className="absolute -right-24 -top-32 size-[480px] rounded-full bg-[hsl(var(--accent)/.24)] blur-3xl" /><div className="absolute bottom-0 left-1/3 size-48 rounded-full bg-[hsl(var(--chart-3)/.08)] blur-3xl" />
        <div className="relative mx-auto grid max-w-[1240px] items-end gap-14 lg:grid-cols-[1.1fr_.9fr]">
          <div className="rise-in"><p className="mono-label mb-5 flex items-center gap-2 text-[hsl(var(--chart-3))]"><span className="size-1.5 rounded-full bg-[hsl(var(--chart-3))]" />Built for decisions made outdoors</p><h1 className="display-serif max-w-4xl text-[clamp(4rem,9vw,8.4rem)] leading-[.82] tracking-[-.055em]">Know what<br /><em className="text-primary">to grow next.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted-foreground">AgroBrain turns the particulars of your farm — soil, water, climate, history — into a clear crop plan that respects your margins.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/dashboard" className="inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3.5 text-sm font-bold text-primary-foreground transition-transform hover:-translate-y-0.5" data-testid="link-start-planning">Start planning <ArrowRight className="size-4" /></Link><a href="#how-it-works" className="inline-flex items-center rounded-xl px-5 py-3.5 text-sm font-bold text-muted-foreground hover:bg-secondary" data-testid="link-learn-more">See how it works</a></div></div>
          <div className="relative rise-in delay-2"><div className="relative ml-auto max-w-[470px] overflow-hidden rounded-[2rem] border border-primary/20 bg-primary p-5 text-primary-foreground shadow-2xl shadow-primary/15 sm:p-7"><div className="absolute -right-16 -top-20 size-64 rounded-full border border-primary-foreground/10" /><div className="absolute -bottom-20 -left-16 size-64 rounded-full border border-primary-foreground/10" /><div className="relative"><div className="flex items-center justify-between border-b border-primary-foreground/15 pb-5"><div><p className="mono-label text-primary-foreground/50">Field note / 014</p><p className="mt-1 text-sm font-bold">Kaveri North · 8.5 acres</p></div><div className="flex size-10 items-center justify-center rounded-xl bg-accent text-accent-foreground"><Sprout className="size-5" /></div></div><div className="py-10"><p className="text-sm text-primary-foreground/60">Strongest fit for Rabi</p><h2 className="display-serif mt-2 text-6xl leading-none">Chickpea</h2><div className="mt-7 flex items-end gap-3"><span className="text-5xl font-extrabold tracking-[-.06em]">86</span><span className="pb-1.5 text-sm text-primary-foreground/60">/ 100 suitability</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-primary-foreground/15"><div className="h-full w-[86%] rounded-full bg-accent" /></div></div><div className="grid grid-cols-2 gap-3 border-t border-primary-foreground/15 pt-5"><div><p className="mono-label text-primary-foreground/45">Est. yield</p><p className="mt-1 font-bold">9–11 q/ac</p></div><div><p className="mono-label text-primary-foreground/45">Est. return</p><p className="mt-1 font-bold text-accent">+31%</p></div></div></div></div><p className="mt-4 text-right text-xs text-muted-foreground">An example advisory, grounded in your inputs.</p></div>
        </div>
      </section>
      <section id="how-it-works" className="border-y border-border bg-card px-6 py-16 sm:px-10 lg:px-16"><div className="mx-auto max-w-[1240px]"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mono-label text-[hsl(var(--chart-3))]">The AgroBrain method</p><h2 className="display-serif mt-3 max-w-md text-4xl leading-tight tracking-[-.03em]">Less guesswork.<br />More field sense.</h2></div><div className="grid gap-8 sm:grid-cols-3">{[{icon: LineChart, title: 'Read the whole field', text: 'Bring soil, water, weather, and crop history into one working picture.'}, {icon: ShieldCheck, title: 'Respect the margin', text: 'Recommendations are weighed against budget, yield, and practical risk.'}, {icon: SunMedium, title: 'Act with timing', text: 'Get a sequence of next steps you can take back to the farm.'}].map(({ icon: Icon, title, text }, i) => <div key={title} className={`rise-in delay-${i + 1}`}><div className="mb-4 flex size-10 items-center justify-center rounded-xl bg-secondary text-primary"><Icon className="size-5" /></div><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></div></div></section>
      <section className="px-6 py-20 sm:px-10 lg:px-16"><div className="mx-auto grid max-w-[1240px] items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="mono-label text-[hsl(var(--chart-3))]">Made for the in-between moments</p><h2 className="display-serif mt-3 text-4xl leading-tight tracking-[-.03em] sm:text-5xl">A clear page before<br />a long day outside.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-muted-foreground">Whether you manage one plot or a portfolio of farms, AgroBrain gives every conversation a place to start — and every recommendation a reason.</p><div className="mt-7 space-y-3">{['Technical inputs that stay understandable', 'Reports you can print, share, and revisit', 'A growing record of your farm decisions'].map(item => <div key={item} className="flex items-center gap-3 text-sm font-semibold"><span className="flex size-5 items-center justify-center rounded-full bg-[hsl(var(--chart-2)/.22)] text-primary"><Check className="size-3" /></span>{item}</div>)}</div></div><div className="field-grid relative min-h-[280px] overflow-hidden rounded-[2rem] border border-border bg-secondary/50 p-8"><div className="absolute right-8 top-8 flex size-20 items-center justify-center rounded-full border border-[hsl(var(--chart-3)/.3)] bg-[hsl(var(--chart-3)/.12)]"><Droplets className="size-8 text-[hsl(var(--chart-3))]" /></div><div className="absolute bottom-8 left-8 max-w-[240px]"><p className="mono-label text-muted-foreground">The useful question</p><p className="display-serif mt-2 text-3xl leading-tight">“What changes if the water arrives late?”</p></div></div></div></section>
      <footer className="flex flex-col justify-between gap-4 border-t border-border px-6 py-7 text-xs text-muted-foreground sm:flex-row sm:px-10 lg:px-16"><Mark compact /><span>Field intelligence for better choices.</span></footer>
    </main>
  </div>;
}